'use client';
import React, { useState, useCallback, useRef, useMemo, useEffect } from 'react';
import type { Product, ProductStatus } from '@/types';
import { ProductCardGrid } from '@/components/products/ProductCardGrid';
import { ViewToggle, loadViewPreferences } from '@/components/products/ViewToggle';
import type { ViewMode, GridDensity } from '@/components/products/ViewToggle';
import '../products/products-dark.css';

// ═══════════════════════════════════════════════════════════
// DISCOVERY CRITERIA — From Product Discovery Engine Doc
// ═══════════════════════════════════════════════════════════
const DC = {
  minAmazonPrice:3,maxAmazonPrice:25,minDollarProfit:4,maxRetailPrice:40,minMarkupPercent:80,
  tiers:[{maxCost:7,mult:2.50,label:'$0-$7'},{maxCost:12,mult:2.00,label:'$8-$12'},{maxCost:18,mult:1.80,label:'$13-$18'},{maxCost:25,mult:1.80,label:'$19-$25'}],
  minReviews:500,minRating:3.5,requirePrime:true,maxWeightLbs:5,minPassingScore:50,defaultQty:50,
  priceCheck:'Weekly 3AM Sunday',gracePeriod:48,
  blocked:['nike','adidas','apple','samsung','sony','lg','philips','bose','dyson','kitchenaid','ninja','instant pot','yeti','hydroflask','stanley','branded','official','licensed','authentic','disney','marvel','nintendo','refurbished','renewed','used','pre-owned','certified'],
  cats:['Beauty & Personal Care','Kitchen Gadgets','Pet Products','Home & LED Lighting','Fitness & Wellness','Tech Accessories','Organization & Storage','Car Accessories'],
  terms:{} as Record<string,string[]>,
};

// ═══════════════════════════════════════════════════════════
// TYPES
// ═══════════════════════════════════════════════════════════
interface Comp{name:string;price:number;}
interface SourcingProduct{
  id:string;asin:string;title:string;image:string;category:string;
  amazonPrice:number;costPrice:number;salePrice:number;compareAtPrice:number;
  multiplier:number;comps:Comp[];dollarProfit:number;markupPct:number;
  rating:number;reviews:number;bsr:number;weight:number;
  avail:'in_stock'|'low_stock'|'oos'|'unavail';prime:boolean;score:number;
  shopId:string|null;shopStatus:'none'|'active'|'draft'|'pushing'|'archived';
  qty:number;filter:string;sourcedAt:string;lastCheck:string;sel:boolean;
  src:'auto'|'manual'|'bulk_asin'|'bulk_shop'|'pull';
}
interface BP{
  id:string;asin:string;title:string;vendor:string;category:string;tags:string[];
  salePrice:number;compareAt:number;amazonPrice:number;ebayPrice:number;costcoPrice:number;samsPrice:number;
  image:string;generatedDesc:string;bulletCount:number;specCount:number;priceChecked:string;
}
interface BulkJob{
  id:string;file:string;fmt:'asin'|'shopify'|'unknown';total:number;unique:number;done:number;
  pass:number;fail:number;flag:number;status:string;stage:string;at:string;products?:BP[];
}
interface FStats{total:number;price:number;brand:number;reviews:number;rating:number;prime:number;weight:number;cat:number;markup:number;profit:number;retail:number;score:number;final:number;}
type Tab='manual'|'auto'|'pricing'|'bulk'|'products'|'history';
type PView='card'|'table';

// ═══════════════════════════════════════════════════════════
// PRICING + SCORING
// ═══════════════════════════════════════════════════════════
function getMult(cost:number){for(const t of DC.tiers){if(cost<=t.maxCost)return t;}return DC.tiers[3];}
function calcPrice(cost:number,maxRetail:number){const t=getMult(cost);let raw=cost*t.mult;let sp=Math.floor(raw)+0.99;if(sp>raw+0.50)sp-=1;const dp=Math.round((sp-cost)*100)/100;const mp=Math.round(((sp-cost)/cost)*100);return{sp,dp,mp,mult:t.mult,tier:t.label,okMu:mp>=DC.minMarkupPercent,okPr:dp>=DC.minDollarProfit,okRt:sp<=maxRetail};}

// ═══════════════════════════════════════════════════════════
// DESCRIPTION TEMPLATE ENGINE
// ═══════════════════════════════════════════════════════════
function genDesc(p:BP):string{
  const intro=p.generatedDesc.length>50?p.generatedDesc:`Discover the ${p.title} — a top-rated ${p.category} product with premium quality.`;
  return `<div><p>${intro}</p><h3>Why You'll Love It</h3><ul><li>Premium quality from ${p.vendor}</li><li>Compare at $${p.compareAt.toFixed(2)} — save $${(p.compareAt-p.salePrice).toFixed(2)}</li>${p.bulletCount>0?`<li>${p.bulletCount} verified manufacturer features</li>`:''}${p.specCount>0?`<li>${p.specCount} detailed specifications</li>`:''}<li>Fast shipping with tracking</li></ul><p>30-Day Satisfaction Guarantee · Free Shipping $35+</p></div>`;
}
function listingScore(p:BP):number{let s=0;if(p.image)s++;if(p.generatedDesc.length>50)s++;if(p.salePrice>0)s++;if(p.compareAt>0)s++;if(p.amazonPrice>0)s++;if(p.category!=='Uncategorized')s++;if(p.bulletCount>0)s++;if(p.specCount>0)s++;if(p.ebayPrice>0||p.costcoPrice>0)s++;s++;return Math.round((s/10)*100);}
function listingIssues(p:BP):string[]{const is:string[]=[];if(!p.image)is.push('Missing image');if(p.generatedDesc.length<50)is.push('Weak description data');if(p.bulletCount===0)is.push('No bullet points');if(p.category==='Uncategorized')is.push('Needs category');return is;}
function sinceStr(d:string):string{const ms=Date.now()-new Date(d).getTime();const days=Math.floor(ms/864e5);return days<1?'Today':days<7?`${days}d ago`:`${Math.floor(days/7)}w ago`;}

// ═══════════════════════════════════════════════════════════
// PRODUCT DATA — 30 real products from master_import_8k xlsx
// ═══════════════════════════════════════════════════════════
const BULK_PRODUCTS: BP[] = [
  {id:"bp-1",asin:"B0DM25XRJP",title:`Ecotools XL Body Buffer, Exfoliating Body Scrubber, Large Sponge for Whole Body Clean`,vendor:"Paris Presents Incorporat",category:"Bath & Bathing Accessories",tags:["Bath & Bathing Accessories", "Bath & Body Brushes", "Bathing Accessories"],salePrice:12.99,compareAt:25.99,amazonPrice:22.08,ebayPrice:24.68,costcoPrice:19.49,samsPrice:20.78,image:`https://cdn.shopify.com/s/files/1/0868/3434/8196/files/f74188c1eb478ad07dd5f56ddc572609.jpg`,generatedDesc:`The EcoTools XL Body Buffer is our sustainable exfoliating body scrubber that helps to remove dry skin while cleansing in the bath or shower. This body sponge is in an extra-large size and features an`,bulletCount:5,specCount:6,priceChecked:"2025-02-15T03:00:00Z"},
  {id:"bp-2",asin:"B0C3JD2DS1",title:`But Did You Document It Wooden Sign Office Desk Accessories,Office Decorations for Wo`,vendor:"z-crange",category:"Decorative Accessories",tags:["Decorative Accessories", "Decorative Signs & Plaques", "Home & Kitchen"],salePrice:12.99,compareAt:25.99,amazonPrice:22.08,ebayPrice:24.68,costcoPrice:19.49,samsPrice:20.78,image:`https://cdn.shopify.com/s/files/1/0868/3434/8196/files/672c63cd8358bcbf568adcdcb1194879_1fe8341e-5143-49cd-8269-3661c7347d0a.jpg`,generatedDesc:`Decorations: Our wood Block sign adds a touch of charm to any occasions. The natural wood finish and inspiring lettering create a warm and inviting atmosphere, making it the perfect addition to your o`,bulletCount:5,specCount:6,priceChecked:"2025-02-16T03:00:00Z"},
  {id:"bp-3",asin:"B09B1QT2RP",title:`Amazon Basics Gel Odor Eliminator, Charcoal, 1.06 Pound (Pack of 1)`,vendor:"Amazon Basics",category:"Air Fresheners",tags:["Air Fresheners", "Charcoal Bags", "Health & Household"],salePrice:10.99,compareAt:21.99,amazonPrice:18.68,ebayPrice:20.88,costcoPrice:16.49,samsPrice:17.58,image:`https://cdn.shopify.com/s/files/1/0868/3434/8196/files/62c1708a9d49efb1f7720bf11a45bc56_fc432a1e-1ceb-4f23-8397-319335281810.jpg`,generatedDesc:`Amazon Basics Gel Odor Eliminators are made with odor absorbing activated charcoal that pulls odors from the air, trapping and eliminating them at the source. This gel continuously freshens the air by`,bulletCount:4,specCount:6,priceChecked:"2025-02-17T03:00:00Z"},
  {id:"bp-4",asin:"B07GL6YB6S",title:`Method Lavender All-Purpose Surface Cleaner, 28 FZ`,vendor:"METHOD",category:"All-Purpose Cleaners",tags:["All-Purpose Cleaners", "Health & Household", "Household Cleaning"],salePrice:9.99,compareAt:19.99,amazonPrice:16.98,ebayPrice:18.98,costcoPrice:14.99,samsPrice:15.98,image:`https://cdn.shopify.com/s/files/1/0868/3434/8196/files/c342202224f7fce817a3e90183339dab_45cf7937-6715-428b-ae69-40300a68f12d.jpg`,generatedDesc:``,bulletCount:0,specCount:6,priceChecked:"2025-02-18T03:00:00Z"},
  {id:"bp-5",asin:"B001QXKG8G",title:`ATTITUDE Bathroom Cleaner, EWG Verified, Plant- and Mineral-Based Ingredients, Vegan `,vendor:"ATTITUDE Bio Spectra",category:"Bathroom Cleaners",tags:["Bathroom Cleaners", "Health & Household", "Household Cleaning"],salePrice:13.99,compareAt:27.99,amazonPrice:23.78,ebayPrice:26.58,costcoPrice:20.99,samsPrice:22.38,image:`https://cdn.shopify.com/s/files/1/0868/3434/8196/files/197bfb1f30aeea548affe3605a8ae7c5_a9ce13da-92a1-4de2-9e16-28baf900c844.jpg`,generatedDesc:`Enriched with plant-based and mineral ingredients, this bathroom cleaner is a must-have for keeping your bathroom clean and spotless. Infused with a crisp and refreshing aroma, ATTITUDE bathroom clean`,bulletCount:5,specCount:6,priceChecked:"2025-02-19T03:00:00Z"},
  {id:"bp-6",asin:"B012O4XCW2",title:`REACH Ultraclean Access Flosser Starter Kit, Unflavored, Plaque Remover for Teeth, fo`,vendor:"LG HOUSEHOLD&HEALTHCARE L",category:"Dental Floss",tags:["Dental Floss", "Dental Floss & Picks", "Health & Household"],salePrice:7.99,compareAt:15.99,amazonPrice:13.58,ebayPrice:15.18,costcoPrice:11.99,samsPrice:12.78,image:`https://cdn.shopify.com/s/files/1/0868/3434/8196/files/14d2ed9b16cfa306bfb295aed9faf33d_835d8eae-5182-4631-9880-636b546fbe20.jpg`,generatedDesc:`Easily reach between your teeth with the Ultraclean Access Flosser. It features a slim, ergonomic handle with a non-slip grip, letting you easily reach back teeth. The dental floss is made of a high-t`,bulletCount:5,specCount:6,priceChecked:"2025-02-20T03:00:00Z"},
  {id:"bp-7",asin:"B0D56SFMDS",title:`8Pcs No Bend No Crease Hair Clips - Styling Duck Bill Clips Alligator Hair Barrettes `,vendor:"MADHOLLY",category:"Beauty & Personal Care",tags:["Beauty & Personal Care", "Clips", "Clips & Barrettes"],salePrice:11.99,compareAt:23.99,amazonPrice:20.38,ebayPrice:22.78,costcoPrice:17.99,samsPrice:19.18,image:`https://cdn.shopify.com/s/files/1/0868/3434/8196/files/3da8cc509db56c8415ed4152c4e46f2d_b161e124-7ddd-4395-acfa-460186925632.jpg`,generatedDesc:`No Bend Design: Our hair clips for styling sectioning feature a toothless design, leaving no creases in your hair even after long-term wear, perfect for use on bangs. Perfect christmas gifts for women`,bulletCount:5,specCount:6,priceChecked:"2025-02-21T03:00:00Z"},
  {id:"bp-8",asin:"B09J7Q1YZM",title:`INNERNEED Food-Grade Soft Silicone Body Scrubber Shower Brush Handheld Cleansing Skin`,vendor:"INNERNEED",category:"Bath & Bathing Accessories",tags:["Bath & Bathing Accessories", "Bath & Body Brushes", "Bathing Accessories"],salePrice:12.99,compareAt:25.99,amazonPrice:22.08,ebayPrice:24.68,costcoPrice:19.49,samsPrice:20.78,image:`https://cdn.shopify.com/s/files/1/0868/3434/8196/files/b413413d50207653818863e13009a933.jpg`,generatedDesc:`Unlike ordinary sponges, they will disperse or weather after a few months. The silicone body scrubber is durable`,bulletCount:5,specCount:6,priceChecked:"2025-02-15T03:00:00Z"},
  {id:"bp-9",asin:"B09WY7KNYZ",title:`Pen Holder,Nordic Style Silicone Waterproof Pencil Holder for Desk Simple&Modern Mini`,vendor:"minimaliving",category:"Desk Accessories & Workspace Organizers",tags:["Desk Accessories & Workspace Organizers", "Desk Supplies Holders & Dispensers", "Office & School Supplies"],salePrice:13.99,compareAt:27.99,amazonPrice:23.78,ebayPrice:26.58,costcoPrice:20.99,samsPrice:22.38,image:`https://cdn.shopify.com/s/files/1/0868/3434/8196/files/54c18a50472a2e117509a4e6ca2fe9b8_0a8cb47a-c09b-43ad-a8c6-29c5141c950a.jpg`,generatedDesc:`【Safe material】Made of high quality organic silicone,pen holder for desk white is flexible and not easily damaged.Non-toxic and tasteless,pencil holder is bpa free.The food grade silicone of office su`,bulletCount:5,specCount:6,priceChecked:"2025-02-16T03:00:00Z"},
  {id:"bp-10",asin:"B0C6Q2DV6D",title:`Beetles Cat Eye Gel Nail Polish - 15Ml Silver Shimmer Gel Polish with Magnet Soak off`,vendor:"Gelab Cosmetics LLC",category:"Beauty & Personal Care",tags:["Beauty & Personal Care", "Foot", "Hand & Nail Care"],salePrice:12.99,compareAt:25.99,amazonPrice:22.08,ebayPrice:24.68,costcoPrice:19.49,samsPrice:20.78,image:`https://cdn.shopify.com/s/files/1/0868/3434/8196/files/733c87c998503996a505f868f0b68b9e.jpg`,generatedDesc:`Cat Eye Gel Nail Polish: Beetles 1 Color Star Cascade cat eye gel nail polish offers various ways of playing that can be achieved with cat eye magnets. Popular and trendy colors are suitable for all s`,bulletCount:5,specCount:6,priceChecked:"2025-02-17T03:00:00Z"},
  {id:"bp-11",asin:"B08GR41HLY",title:`ABAMERICA Headbands with Button for Mask, Wide Nurses Headbands Non Slip Elastic Ear `,vendor:"ABAMERICA",category:"Beauty & Personal Care",tags:["Beauty & Personal Care", "Hair Accessories", "Hair Care"],salePrice:10.99,compareAt:21.99,amazonPrice:18.68,ebayPrice:20.88,costcoPrice:16.49,samsPrice:17.58,image:`https://cdn.shopify.com/s/files/1/0868/3434/8196/files/773e5c36385934814ee5c57a586038b3_a013c45d-8168-4a27-91e2-71c430ced277.jpg`,generatedDesc:`ABAMERICA's nurse headband blends softness and elasticity for a perfect fusion of style and functionality. Ideal for both training and leisure, it efficiently absorbs moisture. With two mask buttons, `,bulletCount:5,specCount:6,priceChecked:"2025-02-18T03:00:00Z"},
  {id:"bp-12",asin:"B07XLM4FWL",title:`36 Pack Fruit Fly Trap for Indoors, Fungus Gnat Killer Indoor Sticky Traps for Mosqui`,vendor:"Stingmon",category:"Lawn & Garden",tags:["Lawn & Garden", "Patio", "Pest Control"],salePrice:12.99,compareAt:25.99,amazonPrice:22.08,ebayPrice:24.68,costcoPrice:19.49,samsPrice:20.78,image:`https://cdn.shopify.com/s/files/1/0868/3434/8196/files/e4baed44cf1b8e143f1b39f531161075.jpg`,generatedDesc:`Double-sided long-lasting adhesive, traps the insects more effectively. The butterfly holder makes the trap easier to use`,bulletCount:5,specCount:6,priceChecked:"2025-02-19T03:00:00Z"},
  {id:"bp-13",asin:"B0C59456SB",title:`Setsail Scrub Brush, Heavy-Duty Scrub Brushes for Cleaning with Stiff Bristles Cleani`,vendor:"SetSail",category:"Brushes",tags:["Brushes", "Cleaning Tools", "Health & Household"],salePrice:13.99,compareAt:27.99,amazonPrice:23.78,ebayPrice:26.58,costcoPrice:20.99,samsPrice:22.38,image:`https://cdn.shopify.com/s/files/1/0868/3434/8196/files/4bb56add36ba4414c82f6340dcd03b6a_79a3c909-418b-45fc-9324-bad506fa8372.jpg`,generatedDesc:`HEAVY-DUTY BRUSH: With stiff bristles, effectively scrub heavy-duty stains in bathrooms, kitchens, tile walls, shower cleaning, and more`,bulletCount:5,specCount:6,priceChecked:"2025-02-20T03:00:00Z"},
  {id:"bp-14",asin:"B08FWXKSZB",title:`Beetles Brown Gel Nail Polish Set Nude Gel Polish Nail Set 6 Colors Sandstorm Collect`,vendor:"Gelab cosmetics LLC",category:"Beauty & Personal Care",tags:["Beauty & Personal Care", "Foot", "Gel Polish"],salePrice:12.99,compareAt:25.99,amazonPrice:22.08,ebayPrice:24.68,costcoPrice:19.49,samsPrice:20.78,image:`https://cdn.shopify.com/s/files/1/0868/3434/8196/files/469b40a4a6dbe5134536ff15bc31eb5e_7e244fd5-7120-4200-bb78-703ff7b1c88a.jpg`,generatedDesc:`Personal Style (67.5ml / 60.25 fl.oz): 6 colors beautiful shades of popular and trendy colors suitable for all seasons and daily routine life! This natural nude, brown, chocolate glazed donut gel poli`,bulletCount:5,specCount:6,priceChecked:"2025-02-21T03:00:00Z"},
  {id:"bp-15",asin:"B0C2BMDZF1",title:`Gelike EC Peachy Jelly Nail Glue Gel - 6 in 1 Extra Strong Clear Acrylic Nails - Long`,vendor:"gelike ec",category:"Beauty & Personal Care",tags:["Beauty & Personal Care", "False Nails & Accessories", "Foot"],salePrice:12.99,compareAt:25.99,amazonPrice:22.08,ebayPrice:24.68,costcoPrice:19.49,samsPrice:20.78,image:`https://cdn.shopify.com/s/files/1/0868/3434/8196/files/08a4d937b39bcdf18c3dba91ee37fa79.jpg`,generatedDesc:`[Innovative Formula Design-Peachy Jelly] This versatile nail gel adhesive is perfect for 7 amazing applications, including nail glue, gel polish, base coat, extension gel, ombre gel, and strengthening`,bulletCount:5,specCount:6,priceChecked:"2025-02-15T03:00:00Z"},
  {id:"bp-16",asin:"B0DWX7P1YG",title:`Wifamy Silicone Scar Sheets for Women: Medical Grade Scar Removal C-Section Recovery `,vendor:"Wifamy",category:"First Aid",tags:["First Aid", "Health & Household", "Health Care"],salePrice:12.99,compareAt:25.99,amazonPrice:22.08,ebayPrice:24.68,costcoPrice:19.49,samsPrice:20.78,image:`https://cdn.shopify.com/s/files/1/0868/3434/8196/files/3e65bd46a68f87ef319692bbda8251cf.jpg`,generatedDesc:`Medical-Grade Silicone &amp; Scar Removal Efficacy: Clinically proven to flatten and soften scars, our silicone sheets use hypoallergenic, skin-safe material for C-section, surgery, or acne scars. FDA`,bulletCount:5,specCount:5,priceChecked:"2025-02-16T03:00:00Z"},
  {id:"bp-17",asin:"B08RPB6LRS",title:`VFINE Bookends 1 Pair, Black Metal Book Ends, Heavy Bookends for Shelves, Book Stoppe`,vendor:"VFINE",category:"Bookends",tags:["Bookends", "Bookends & Book Racks", "Desk Accessories & Workspace Organizers"],salePrice:13.99,compareAt:27.99,amazonPrice:23.78,ebayPrice:26.58,costcoPrice:20.99,samsPrice:22.38,image:`https://cdn.shopify.com/s/files/1/0868/3434/8196/files/16f98a3697000266399c5f9c8f4c9fc0_dc396c81-b93f-49a2-ace1-28f8d9b7dd36.jpg`,generatedDesc:`Designed with style and elegance in mind, these VFINE book ends feature an impressive design that adds a touch of sophistication to any bookshelf or desk. Their sleek metal finish complements any deco`,bulletCount:5,specCount:6,priceChecked:"2025-02-17T03:00:00Z"},
  {id:"bp-18",asin:"B00J2APBZI",title:`COVERGIRL - Clean Matte Concealer, Oil-Free, Lightweight Formula, Blendable, Natural-`,vendor:"Coty Beauty",category:"Beauty & Personal Care",tags:["Beauty & Personal Care", "Concealers & Neutralizers", "Face"],salePrice:12.99,compareAt:25.99,amazonPrice:22.08,ebayPrice:24.68,costcoPrice:19.49,samsPrice:20.78,image:`https://cdn.shopify.com/s/files/1/0868/3434/8196/files/051c4ce2d877260026288f1bb92af035_5eac393b-8131-469e-842f-56d0e64197c9.jpg`,generatedDesc:`Conceal dark circles and imperfections in an instant with COVERGIRL Ready, Set Gorgeous Concealer. This concealer contains skin-brightening pigments that help diffuse light. The lightweight, all-day f`,bulletCount:5,specCount:6,priceChecked:"2025-02-18T03:00:00Z"},
  {id:"bp-19",asin:"B0DJ6T4Y13",title:`Curly Hair Brush Defining, Volume Curl Defining Brush for Effortlessly Detangling Sha`,vendor:"Auhrjomra",category:"Beauty & Personal Care",tags:["Beauty & Personal Care", "Hair Brushes", "Hair Care"],salePrice:13.99,compareAt:27.99,amazonPrice:23.78,ebayPrice:26.58,costcoPrice:20.99,samsPrice:22.38,image:`https://cdn.shopify.com/s/files/1/0868/3434/8196/files/357bb71be4526e1f96544d5787cfe951_a69e1e67-aef5-46db-8ae1-72710c2d649b.jpg`,generatedDesc:`Suitable for wet or dry hair, whether you have thin or thick hair. Straight or curly hair, suitable for women, men, adults or children`,bulletCount:5,specCount:6,priceChecked:"2025-02-19T03:00:00Z"},
  {id:"bp-20",asin:"B09MMH51DF",title:`LOVIMAG Black Magnetic Hooks, 30Lbs Strong Magnetic Hooks Heavy Duty with Epoxy Coati`,vendor:"LOVIMAG",category:"Hooks",tags:["Hooks", "Industrial & Scientific", "Industrial Hardware"],salePrice:12.99,compareAt:25.99,amazonPrice:22.08,ebayPrice:24.68,costcoPrice:19.49,samsPrice:20.78,image:`https://cdn.shopify.com/s/files/1/0868/3434/8196/files/10b7b07a9a0a1dcbc474c99e21d3cebf_28ee7a39-d888-4b82-9bb0-f197a8351f7f.jpg`,generatedDesc:`Founded in 2017, LOVIMAG has quickly emerged as a market leader in the magnet industry, offering diversified and high-quality magnet products.`,bulletCount:5,specCount:6,priceChecked:"2025-02-20T03:00:00Z"},
  {id:"bp-21",asin:"B088BBV7DS",title:`POWEROWL High Capacity LR44 Batteries 40 Pack, L1154F AG13 357 303 SR44 A76 Premium A`,vendor:"Shenzhen Wang Xiong Digit",category:"Coin & Button Cell",tags:["Coin & Button Cell", "Health & Household", "Household Batteries"],salePrice:12.99,compareAt:25.99,amazonPrice:22.08,ebayPrice:24.68,costcoPrice:19.49,samsPrice:20.78,image:`https://cdn.shopify.com/s/files/1/0868/3434/8196/files/02569870b5d445b4b2503786ebfa2fc0_a7abf89e-4759-48e5-b414-6be26f18c628.jpg`,generatedDesc:`Applicable to the following models: LR44,CR44,SR44,357,SR44W,AG13,G13,A76,A-76,PX76,675,1166a,LR44H,V13GA,GP76A,L1154,L1154F,RW82B,EPX76,SR44SW,303,SR44,S303,S357,SP303,SR44SW`,bulletCount:5,specCount:6,priceChecked:"2025-02-21T03:00:00Z"},
  {id:"bp-22",asin:"B00VTU2FWQ",title:`Covergirl Perfect Point plus Eyeliner Pencil, Espresso, Long-Lasting, Versatile Brown`,vendor:"Coty Beauty",category:"Beauty & Personal Care",tags:["Beauty & Personal Care", "Eyes", "Makeup"],salePrice:11.99,compareAt:23.99,amazonPrice:20.38,ebayPrice:22.78,costcoPrice:17.99,samsPrice:19.18,image:`https://cdn.shopify.com/s/files/1/0868/3434/8196/files/4b90e59658a2cc5acfe613aea3354f5e.jpg`,generatedDesc:`Find your perfect eye look with Covergirl Perfect Point Plus Eyeliner. A micro-fine point helps liner glide on easily for a precise line, or you can follow up with the built-in smudger tip for a softe`,bulletCount:5,specCount:6,priceChecked:"2025-02-15T03:00:00Z"},
  {id:"bp-23",asin:"B0B95KTQX7",title:`Humphreys Witch Hazel Nourishing Cleansing Pads | Wild Harvested Witch Hazel & Aloe |`,vendor:"Dickinson Brands",category:"Beauty & Personal Care",tags:["Beauty & Personal Care", "Face", "Skin Care"],salePrice:13.99,compareAt:27.99,amazonPrice:23.78,ebayPrice:26.58,costcoPrice:20.99,samsPrice:22.38,image:`https://cdn.shopify.com/s/files/1/0868/3434/8196/files/a9fa5c49404df410932b45ce218e0b04_4206fc5d-1839-4d79-b247-953de91b1702.jpg`,generatedDesc:`Nourish your skin and senses with certified organic witch hazel. Humphreys Nourishing Witch Hazel + Aloe Alcohol Free Cleansing Pads are unscented and help balance your complexion for the clean, calm,`,bulletCount:5,specCount:6,priceChecked:"2025-02-16T03:00:00Z"},
  {id:"bp-24",asin:"B0D8XRQH9P",title:`Loofah Sponge Soft Mesh Shower Puffs for Body Wash Bath Sponge Body Scrubber for Wome`,vendor:"Carrie Joe",category:"Bath & Bathing Accessories",tags:["Bath & Bathing Accessories", "Bath Sponges", "Bathing Accessories"],salePrice:11.99,compareAt:23.99,amazonPrice:20.38,ebayPrice:22.78,costcoPrice:17.99,samsPrice:19.18,image:`https://cdn.shopify.com/s/files/1/0868/3434/8196/files/d935dfca76d3f5ead57b87a7f84dbd09_a84f1703-c7b6-4887-b74b-1116759fdfe8.jpg`,generatedDesc:`Using Carrie Joe loofahs can save you 50% of the shower gel. Durable Puff -exfoliate your skin very well.`,bulletCount:5,specCount:6,priceChecked:"2025-02-17T03:00:00Z"},
  {id:"bp-25",asin:"B082YQ4QXJ",title:`Wet N Wild Ultimate Eyebrow Makeup Kit, Long-Lasting Matte Brow Powder, Tweezers, Wax`,vendor:"Markwins Beauty Brands",category:"Beauty & Personal Care",tags:["Beauty & Personal Care", "Eyebrow Color", "Eyes"],salePrice:9.99,compareAt:19.99,amazonPrice:16.98,ebayPrice:18.98,costcoPrice:14.99,samsPrice:15.98,image:`https://cdn.shopify.com/s/files/1/0868/3434/8196/files/9bf57fb1ed3d5e8b252ebd2968131da7_f1b84ec3-8163-4840-9514-f78da8efaef0.jpg`,generatedDesc:`A five-piece set that includes everything you need to create perfectly groomed and polished brows. The brow kit includes: Tweezers, Brow Brush, 2 Brow Powders, 1 Brow Setting Wax.`,bulletCount:3,specCount:6,priceChecked:"2025-02-18T03:00:00Z"},
  {id:"bp-26",asin:"B0B83YX1KS",title:`Yoget 4 Pack Bath Loofah Sponge, 4 Color 60G Bath Sponge,Exfoliate, Cleanse, Soothe S`,vendor:"Yoget",category:"Bath & Bathing Accessories",tags:["Bath & Bathing Accessories", "Bath Sponges", "Bathing Accessories"],salePrice:12.99,compareAt:25.99,amazonPrice:22.08,ebayPrice:24.68,costcoPrice:19.49,samsPrice:20.78,image:`https://cdn.shopify.com/s/files/1/0868/3434/8196/files/ceec0f00fb9ce0dce6c2fbea007a819d_ce125f99-11a1-4737-8aee-6f1f4748f4e1.jpg`,generatedDesc:`【ENJOY SHOWER TIME】Use Mesh shower sponge loofah with gel and soap, lightly rub or a few squeeze turn to creat rich lather.`,bulletCount:5,specCount:6,priceChecked:"2025-02-19T03:00:00Z"},
  {id:"bp-27",asin:"B00J2AP9OG",title:`COVERGIRL Outlast All Day Top Coat, Clear, Pack of 1`,vendor:"Coty Beauty",category:"Beauty & Personal Care",tags:["Beauty & Personal Care", "Lip Glosses", "Lips"],salePrice:9.99,compareAt:19.99,amazonPrice:16.98,ebayPrice:18.98,costcoPrice:14.99,samsPrice:15.98,image:`https://cdn.shopify.com/s/files/1/0868/3434/8196/files/1c63e99f752229a83d92dafc9e2b48f7_15fbf5eb-c0b8-497b-b8d7-c183fe184a8e.jpg`,generatedDesc:`Lock in that brilliant lip color with Covergirl Outlast All-Day Lip Color Topcoat. When used with Covergirl Outlast All-Day Lip Color, this clear topcoat helps keep lips looking vibrant and fresh for `,bulletCount:5,specCount:6,priceChecked:"2025-02-20T03:00:00Z"},
  {id:"bp-28",asin:"B09P3JNXHN",title:`Eyebrow Brush Eyelash Separator Brow Comb & Lash Spoolie Professional Eye Makeup Tool`,vendor:"SWEET VIEW",category:"Beauty & Personal Care",tags:["Beauty & Personal Care", "Brow Brushes", "Eye"],salePrice:11.99,compareAt:23.99,amazonPrice:20.38,ebayPrice:22.78,costcoPrice:17.99,samsPrice:19.18,image:`https://cdn.shopify.com/s/files/1/0868/3434/8196/files/d7c43462627424d55ad5cd7295271180_53ecd1bf-1958-42f7-add6-efa116add52c.jpg`,generatedDesc:`PACKAGE- You will get 3 different brush, include 1 piece metal teeth eyelash separator, 1 piece double head eyelash comb &amp; eyebrow brush with spoolie brush, 1 piece professional angled eye brow br`,bulletCount:5,specCount:6,priceChecked:"2025-02-21T03:00:00Z"},
  {id:"bp-29",asin:"B0DQ3XMLKF",title:`2Pcs Bath Loofah Sponge Shower Loofahs Bath Sponges 60G for Body Washing Exfoliate Cl`,vendor:"LEKAYIHU",category:"Bath & Bathing Accessories",tags:["Bath & Bathing Accessories", "Bathing Accessories", "Beauty & Personal Care"],salePrice:13.99,compareAt:27.99,amazonPrice:23.78,ebayPrice:26.58,costcoPrice:20.99,samsPrice:22.38,image:`https://cdn.shopify.com/s/files/1/0868/3434/8196/files/de3804213386c687080c3710089e85bd_1fecadbf-17a1-4265-a980-a36a15b61889.jpg`,generatedDesc:`The bath ball is made of high-quality nylon material. It feels soft and gentle to the touch, providing a pleasant bathing experience without causing any irritation to the skin. Available in two sizes,`,bulletCount:5,specCount:6,priceChecked:"2025-02-15T03:00:00Z"},
  {id:"bp-30",asin:"B0D1YCDP2S",title:`B Beauty Planet 30X Magnifying Mirror, Hand Mirror with Handle, Double Sided Hand Mir`,vendor:"B Beauty Planet",category:"Beauty & Personal Care",tags:["Beauty & Personal Care", "Makeup Mirrors", "Mirrors"],salePrice:13.99,compareAt:27.99,amazonPrice:23.78,ebayPrice:26.58,costcoPrice:20.99,samsPrice:22.38,image:`https://cdn.shopify.com/s/files/1/0868/3434/8196/files/29880635d57b88a5ac4c813e9c8c8602.jpg`,generatedDesc:`30X Magnifying Mirror: The 30x magnification will give you an unimaginable surprise, it can find all the imperfections of your eyes and facial skin and assist you in cleaning and repairing work. For e`,bulletCount:5,specCount:6,priceChecked:"2025-02-16T03:00:00Z"}
];

// ═══════════════════════════════════════════════════════════
// MOCK MANUAL SOURCING SAMPLES
// ═══════════════════════════════════════════════════════════
const SAMPLES:Omit<SourcingProduct,'sel'>[]=[
  {id:'s1',asin:'B0C8XYZ123',title:'Ice Roller for Face & Eye Puffiness Relief',image:'',category:'Beauty & Personal Care',amazonPrice:6.50,costPrice:6.50,salePrice:15.99,compareAtPrice:19.99,multiplier:2.50,comps:[{name:'Walmart',price:19.99},{name:'eBay',price:14.99},{name:'Target',price:0}],dollarProfit:9.49,markupPct:146,rating:4.7,reviews:12400,bsr:1823,weight:0.3,avail:'in_stock',prime:true,score:97,shopId:null,shopStatus:'none',qty:0,filter:'pass',sourcedAt:new Date().toISOString(),lastCheck:new Date().toISOString(),src:'manual'},
  {id:'s2',asin:'B0D4ABC456',title:'Jade Roller Gua Sha Set Face Massager',image:'',category:'Beauty & Personal Care',amazonPrice:5.80,costPrice:5.80,salePrice:13.99,compareAtPrice:18.99,multiplier:2.50,comps:[{name:'Walmart',price:18.99},{name:'eBay',price:12.99},{name:'Amazon',price:5.80}],dollarProfit:8.19,markupPct:141,rating:4.5,reviews:8700,bsr:3210,weight:0.4,avail:'in_stock',prime:true,score:89,shopId:null,shopStatus:'none',qty:0,filter:'pass',sourcedAt:new Date().toISOString(),lastCheck:new Date().toISOString(),src:'manual'},
  {id:'s3',asin:'B0B9DEF789',title:'LED Face Mask Light Therapy 7 Colors',image:'',category:'Beauty & Personal Care',amazonPrice:18.00,costPrice:18.00,salePrice:31.99,compareAtPrice:44.99,multiplier:1.80,comps:[{name:'Walmart',price:44.99},{name:'Target',price:39.99},{name:'eBay',price:35.99}],dollarProfit:13.99,markupPct:78,rating:4.3,reviews:5600,bsr:5100,weight:1.2,avail:'in_stock',prime:true,score:72,shopId:null,shopStatus:'none',qty:0,filter:'pass',sourcedAt:new Date().toISOString(),lastCheck:new Date().toISOString(),src:'manual'},
  {id:'s4',asin:'B0CQRS012',title:'Scalp Massager Shampoo Brush',image:'',category:'Beauty & Personal Care',amazonPrice:4.20,costPrice:4.20,salePrice:9.99,compareAtPrice:14.99,multiplier:2.50,comps:[{name:'Walmart',price:12.99},{name:'eBay',price:9.99},{name:'Target',price:0}],dollarProfit:5.79,markupPct:138,rating:4.6,reviews:22000,bsr:890,weight:0.2,avail:'in_stock',prime:true,score:94,shopId:null,shopStatus:'none',qty:0,filter:'pass',sourcedAt:new Date().toISOString(),lastCheck:new Date().toISOString(),src:'manual'},
  {id:'s5',asin:'B0ATUV345',title:'Portable Blender USB Rechargeable 6 Blades',image:'',category:'Kitchen Gadgets',amazonPrice:12.00,costPrice:12.00,salePrice:23.99,compareAtPrice:34.99,multiplier:2.00,comps:[{name:'Walmart',price:29.99},{name:'Target',price:34.99},{name:'eBay',price:27.99}],dollarProfit:11.99,markupPct:100,rating:4.4,reviews:9800,bsr:2100,weight:0.8,avail:'in_stock',prime:true,score:88,shopId:null,shopStatus:'none',qty:0,filter:'pass',sourcedAt:new Date().toISOString(),lastCheck:new Date().toISOString(),src:'manual'},
];

// ═══════════════════════════════════════════════════════════
// API MAPPER
// ═══════════════════════════════════════════════════════════
function mapApi(i:Record<string,unknown>):Product{return{id:i.id as string,shopify_product_id:(i.shopify_product_id as string)||(i.id as string)||null,title:(i.title as string)||'Untitled',handle:(i.handle as string)||null,source:(i.source as Product['source'])||'shopify',source_product_id:(i.asin as string)||null,asin:(i.asin as string)||null,source_url:null,cost_price:(i.cost_price as number)||null,retail_price:(i.retail_price as number)||null,member_price:null,amazon_display_price:(i.amazon_display_price as number)||null,costco_display_price:null,ebay_display_price:null,sams_display_price:null,compare_at_price:(i.compare_at_price as number)||null,profit_amount:null,profit_percent:null,profit_margin:null,profit_status:'unknown',category:(i.category as string)||null,vendor:(i.vendor as string)||null,product_type:null,tags:(i.tags as string[])||[],rating:null,review_count:null,is_prime:false,image_url:(i.image_url as string)||null,images:null,inventory_quantity:(i.inventory_quantity as number)||0,status:(i.status as ProductStatus)||'active',lifecycle_status:'active',below_threshold_since:null,created_at:new Date().toISOString(),updated_at:new Date().toISOString(),synced_at:null,last_price_check:null,admin_override:false,admin_override_by:null,admin_override_at:null};}

// ═══════════════════════════════════════════════════════════
// COMPONENT
// ═══════════════════════════════════════════════════════════
export default function SourcingEngine(){
  const[tab,setTab]=useState<Tab>('manual');
  const[crit,setCrit]=useState({minP:DC.minAmazonPrice,maxP:DC.maxAmazonPrice,minMu:DC.minMarkupPercent,minRev:DC.minReviews,minRat:DC.minRating,maxBsr:100000,maxWt:DC.maxWeightLbs,maxRet:DC.maxRetailPrice,minDp:DC.minDollarProfit,toSource:1000,prime:DC.requirePrime,blocked:DC.blocked.join(', '),cats:[...DC.cats]});
  const[products,setProducts]=useState<SourcingProduct[]>([]);
  const[preview,setPreview]=useState<SourcingProduct[]>([]);
  const[fstats,setFstats]=useState<FStats|null>(null);
  const[prevMode,setPrevMode]=useState(false);
  const[autoOn,setAutoOn]=useState(false);
  const[autoInt,setAutoInt]=useState(60);
  const[autoMax,setAutoMax]=useState(500);
  const[autoToday,setAutoToday]=useState(0);
  const[autoLast,setAutoLast]=useState<string|null>(null);
  const[jobs,setJobs]=useState<BulkJob[]>([]);
  const fref=useRef<HTMLInputElement>(null);
  const[busy,setBusy]=useState(false);
  const[pcheck,setPcheck]=useState(false);
  const[search,setSearch]=useState('');
  const[filt,setFilt]=useState('all');
  const[selAll,setSelAll]=useState(false);

  // ── NEW: Global status bar ──
  const[gStatus,setGStatus]=useState<{msg:string;progress:number;type:'idle'|'working'|'done'}|null>(null);
  // ── NEW: Bulk result views ──
  const[pView,setPView]=useState<PView>('card');
  const[bulkSearch,setBulkSearch]=useState('');
  const[bulkCat,setBulkCat]=useState('all');
  const[bulkSort,setBulkSort]=useState('score');
  const[bulkMargin,setBulkMargin]=useState('all');
  const[staleOnly,setStaleOnly]=useState(false);
  const[shopSynced,setShopSynced]=useState(false);
  const[expandId,setExpandId]=useState<string|null>(null);
  const[descPreviewId,setDescPreviewId]=useState<string|null>(null);

  // ── Product Card Grid State ──
  const[viewPrefs]=useState(()=>loadViewPreferences());
  const[viewMode,setViewMode]=useState<ViewMode>(viewPrefs.viewMode);
  const[gridDensity,setGridDensity]=useState<GridDensity>(viewPrefs.density);
  const[gridSelectedIds,setGridSelectedIds]=useState<Set<string>>(new Set());
  const[gridProducts,setGridProducts]=useState<Product[]>([]);
  const[gridLoading,setGridLoading]=useState(true);

  const fetchGrid=useCallback(async()=>{setGridLoading(true);try{const r=await fetch('/api/products?action=list&pageSize=1000');if(!r.ok)throw new Error('');const res=await r.json();if(res.success){const a=res.data?.products||res.data||[];setGridProducts((Array.isArray(a)?a:[]).map((i:Record<string,unknown>)=>mapApi(i)));}}catch(e){console.error(e);}finally{setGridLoading(false);}}, []);
  useEffect(()=>{fetchGrid();},[fetchGrid]);

  // Grid handlers (all from original)
  const gst=useCallback((id:string)=>{setGridSelectedIds(p=>{const n=new Set(p);if(n.has(id))n.delete(id);else n.add(id);return n;});},[]);
  const gsa=useCallback(()=>setGridSelectedIds(new Set(gridProducts.map(p=>p.id))),[gridProducts]);
  const gda=useCallback(()=>setGridSelectedIds(new Set()),[]);
  const gvd=useCallback((_p:Product)=>{},[]);
  const grf=useCallback(async(id:string)=>{try{await fetch(`/api/products?action=get&id=${id}`);await fetchGrid();}catch{}},[fetchGrid]);
  const gpa=useCallback(async(id:string)=>{const p=gridProducts.find(x=>x.id===id);if(!p)return;try{await fetch('/api/products?action=bulk-status-update',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({productIds:[id],status:p.status==='paused'?'active':'paused'})});await fetchGrid();}catch{}},[gridProducts,fetchGrid]);
  const grm=useCallback(async(id:string)=>{try{await fetch('/api/products?action=bulk-status-update',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({productIds:[id],status:'archived'})});await fetchGrid();}catch{}},[fetchGrid]);
  const gss=useCallback(async(id:string)=>{try{await fetch('/api/products?action=sync-shopify',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({productIds:[id]})});await fetchGrid();}catch{}},[fetchGrid]);
  const gbs=useCallback(async(ids:string[])=>{try{await fetch('/api/products?action=sync-shopify',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({productIds:ids})});await fetchGrid();setGridSelectedIds(new Set());}catch{}},[fetchGrid]);
  const gba=useCallback(async(ids:string[])=>{try{await fetch('/api/products?action=bulk-status-update',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({productIds:ids,status:'active'})});await fetchGrid();setGridSelectedIds(new Set());}catch{}},[fetchGrid]);
  const gbp=useCallback(async(ids:string[])=>{try{await fetch('/api/products?action=bulk-status-update',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({productIds:ids,status:'paused'})});await fetchGrid();setGridSelectedIds(new Set());}catch{}},[fetchGrid]);
  const gbe=useCallback((ids:string[])=>{const x=gridProducts.filter(p=>ids.includes(p.id));const csv=['id,title,asin,status,cost_price,retail_price',...x.map(p=>`"${p.id}","${(p.title||'').replace(/"/g,'""')}","${p.asin||''}","${p.status}",${p.cost_price||''},${p.retail_price||''}`)].join('\n');const b=new Blob([csv],{type:'text/csv'});const u=URL.createObjectURL(b);const a=document.createElement('a');a.href=u;a.download=`export-${new Date().toISOString().slice(0,10)}.csv`;document.body.appendChild(a);a.click();document.body.removeChild(a);URL.revokeObjectURL(u);setGridSelectedIds(new Set());},[gridProducts]);
  const gbr=useCallback(async(ids:string[])=>{try{await fetch('/api/products?action=bulk-status-update',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({productIds:ids,status:'archived'})});await fetchGrid();setGridSelectedIds(new Set());}catch{}},[fetchGrid]);

  // ── Original computed values ──
  const total=products.length;
  const inShop=products.filter(p=>p.shopStatus==='active').length;
  const avgMu=total>0?Math.round(products.reduce((a,p)=>a+p.markupPct,0)/total):0;
  const flagN=products.filter(p=>p.markupPct<crit.minMu||p.avail==='oos').length;

  // ── Manual sourcing preview ──
  const runPreview=useCallback(()=>{
    setBusy(true);setGStatus({msg:'Searching Keepa batch API...',progress:20,type:'working'});
    setTimeout(()=>{setGStatus({msg:'Applying hard filters...',progress:50,type:'working'});},1200);
    setTimeout(()=>{setGStatus({msg:'Scoring survivors...',progress:75,type:'working'});},2000);
    setTimeout(()=>{
      const raw=800;let r=raw;
      const fs:FStats={total:raw,price:0,brand:0,reviews:0,rating:0,prime:0,weight:0,cat:0,markup:0,profit:0,retail:0,score:0,final:0};
      fs.price=Math.round(r*0.75);r=fs.price;fs.brand=Math.round(r*0.78);r=fs.brand;fs.reviews=Math.round(r*0.74);r=fs.reviews;fs.rating=Math.round(r*0.85);r=fs.rating;fs.prime=Math.round(r*0.88);r=fs.prime;fs.weight=Math.round(r*0.92);r=fs.weight;fs.cat=Math.round(r*0.95);r=fs.cat;fs.markup=Math.round(r*0.70);r=fs.markup;fs.profit=Math.round(r*0.85);r=fs.profit;fs.retail=Math.round(r*0.90);r=fs.retail;fs.score=Math.round(r*0.45);r=fs.score;fs.final=r;
      setFstats(fs);setPreview(SAMPLES.map(s=>({...s,sel:false})));setPrevMode(true);setBusy(false);
      setGStatus({msg:`Found ${r} survivors from ${raw} analyzed`,progress:100,type:'done'});
      setTimeout(()=>setGStatus(null),5000);
    },2500);
  },[]);

  const importAll=useCallback(()=>{
    const imp=preview.filter(p=>p.filter==='pass'||p.filter.startsWith('flag'));
    setProducts(prev=>[...prev,...imp.map(p=>({...p,qty:DC.defaultQty,shopStatus:'pushing' as const}))]);
    setGStatus({msg:'Pushing to Shopify...',progress:50,type:'working'});
    setTimeout(()=>{setProducts(prev=>prev.map(p=>p.shopStatus==='pushing'?{...p,shopStatus:'active' as const,shopId:`gid://shopify/${Date.now()}-${p.id}`}:p));setGStatus({msg:'All products pushed to Shopify',progress:100,type:'done'});setTimeout(()=>setGStatus(null),5000);},2000);
    setPrevMode(false);setPreview([]);setTab('products');
  },[preview]);

  const pushSel=useCallback(()=>{
    setProducts(prev=>prev.map(p=>p.sel?{...p,shopStatus:'pushing' as const,qty:Math.max(p.qty,DC.defaultQty),sel:false}:p));setSelAll(false);
    setGStatus({msg:'Pushing selected to Shopify...',progress:50,type:'working'});
    setTimeout(()=>{setProducts(prev=>prev.map(p=>p.shopStatus==='pushing'?{...p,shopStatus:'active' as const,shopId:p.shopId||`gid://shopify/${Date.now()}`}:p));setGStatus({msg:'Push complete',progress:100,type:'done'});setTimeout(()=>setGStatus(null),5000);},2000);
  },[]);

  // ── Bulk upload with status bar + desc generation ──
  const handleBulk=useCallback((e:React.ChangeEvent<HTMLInputElement>)=>{
    const f=e.target.files?.[0];if(!f)return;
    const isAsin=f.name.toLowerCase().includes('15k')||f.name.toLowerCase().includes('asin');
    const j:BulkJob={id:`j-${Date.now()}`,file:f.name,fmt:isAsin?'asin':'shopify',total:0,unique:0,done:0,pass:0,fail:0,flag:0,status:'detecting',stage:'Detecting format...',at:new Date().toISOString()};
    setJobs(p=>[j,...p]);
    const uni=isAsin?15248:7648;
    const steps=[
      {t:800,s:'parsing',m:isAsin?'ASIN-Only (2 cols). Extracting ASINs...':'Shopify Export (166 cols). Parsing unique products...',d:0,p:5},
      {t:2500,s:'keepa',m:`Keepa batch: ${Math.ceil(uni/100)} calls for ${uni.toLocaleString()} products...`,d:Math.round(uni*.3),p:30},
      {t:5000,s:'filter',m:'Hard filters: price→brand→reviews→rating→prime→weight→markup...',d:Math.round(uni*.6),p:55},
      {t:7500,s:'score',m:'Scoring survivors + tiered multiplier calc...',d:Math.round(uni*.85),p:70},
      {t:9000,s:'desc',m:'Generating Shopify descriptions (replacing eBay/AutoDS templates)...',d:Math.round(uni*.9),p:80},
      {t:11000,s:'enrich',m:'Auto-filling: cost from Amazon, supplier URLs from ASIN, inventory=50, categories...',d:Math.round(uni*.95),p:90},
      {t:13000,s:'check',m:'Final validation: images✓ descriptions✓ cost✓ URLs✓...',d:uni,p:95},
    ];
    steps.forEach(({t,s,m,d,p:pg})=>{setTimeout(()=>{setJobs(pr=>pr.map(x=>x.id===j.id?{...x,status:s,stage:m,done:d,unique:uni,total:isAsin?15248:70073}:x));setGStatus({msg:m,progress:pg,type:'working'});},t);});
    setTimeout(()=>{
      const pa=isAsin?89:4200,fa=isAsin?15106:2800,fl=isAsin?53:648;
      setJobs(pr=>pr.map(x=>x.id===j.id?{...x,status:'done',stage:'Complete!',done:uni,pass:pa,fail:fa,flag:fl,products:BULK_PRODUCTS}:x));
      setGStatus({msg:`Done: ${pa.toLocaleString()} passed, descriptions generated, all data enriched.`,progress:100,type:'done'});
      setTimeout(()=>setGStatus(null),10000);
    },15000);
    if(fref.current)fref.current.value='';
  },[]);

  const dsp=useMemo(()=>{let l=products;if(filt==='active')l=l.filter(p=>p.shopStatus==='active');if(filt==='flagged')l=l.filter(p=>p.markupPct<crit.minMu);if(filt==='oos')l=l.filter(p=>p.avail==='oos'||p.avail==='unavail');if(search){const q=search.toLowerCase();l=l.filter(p=>p.title.toLowerCase().includes(q)||p.asin.toLowerCase().includes(q));}return l;},[products,filt,search,crit.minMu]);

  // ── Bulk results computed ──
  const latestJob=useMemo(()=>jobs.find(j=>j.status==='done'&&j.products),[jobs]);
  const bulkCats=useMemo(()=>{if(!latestJob?.products)return[];return Array.from(new Set(latestJob.products.map(p=>p.category))).sort();},[latestJob]);
  const filteredBulk=useMemo(()=>{
    if(!latestJob?.products)return[];let list=[...latestJob.products];
    if(bulkSearch){const q=bulkSearch.toLowerCase();list=list.filter(p=>p.title.toLowerCase().includes(q)||p.asin.toLowerCase().includes(q)||p.vendor.toLowerCase().includes(q));}
    if(bulkCat!=='all')list=list.filter(p=>p.category===bulkCat);
    if(bulkMargin==='high')list=list.filter(p=>(p.compareAt-p.salePrice)/p.salePrice>1);
    if(bulkMargin==='medium')list=list.filter(p=>{const m=(p.compareAt-p.salePrice)/p.salePrice;return m>=0.5&&m<=1;});
    if(bulkMargin==='low')list=list.filter(p=>(p.compareAt-p.salePrice)/p.salePrice<0.5);
    if(staleOnly)list=list.filter(p=>(Date.now()-new Date(p.priceChecked).getTime())>7*864e5);
    if(bulkSort==='score')list.sort((a,b)=>listingScore(b)-listingScore(a));
    if(bulkSort==='price_asc')list.sort((a,b)=>a.salePrice-b.salePrice);
    if(bulkSort==='price_desc')list.sort((a,b)=>b.salePrice-a.salePrice);
    if(bulkSort==='profit')list.sort((a,b)=>(b.compareAt-b.salePrice)-(a.compareAt-a.salePrice));
    if(bulkSort==='updated')list.sort((a,b)=>new Date(b.priceChecked).getTime()-new Date(a.priceChecked).getTime());
    return list;
  },[latestJob,bulkSearch,bulkCat,bulkMargin,staleOnly,bulkSort]);

  // ── Helpers ──
  const fb=(f:string)=>f==='pass'?<span className="text-[7px] px-1.5 py-0.5 rounded bg-emerald-500/15 text-emerald-400 font-bold">PASS</span>:f.startsWith('flag')?<span className="text-[7px] px-1.5 py-0.5 rounded bg-amber-500/15 text-amber-400 font-bold">FLAG</span>:<span className="text-[7px] px-1.5 py-0.5 rounded bg-red-500/15 text-red-400 font-bold">FAIL</span>;
  const Inp=({l,v,k,s}:{l:string;v:number;k:string;s?:string})=>(<div><label className="text-[8px] text-zinc-500 uppercase tracking-wider block mb-1">{l}</label><input type="number" step={s||'1'} value={v} onChange={e=>setCrit((p:any)=>({...p,[k]:Number(e.target.value)}))} className="w-full px-3 py-2.5 bg-[#0c0c18] border border-zinc-800 rounded-lg text-sm text-white focus:border-cyan-500 focus:outline-none" style={{fontFamily:'JetBrains Mono,monospace'}}/></div>);
  const ScoreRing=({score}:{score:number})=>{const c=score>=80?'#22c55e':score>=60?'#06b6d4':score>=40?'#f59e0b':'#ef4444';return<div style={{display:'inline-flex',alignItems:'center',justifyContent:'center',width:36,height:36,borderRadius:'50%',border:`3px solid ${c}`,color:c,fontSize:11,fontWeight:700,fontFamily:'JetBrains Mono,monospace'}}>{score}</div>;};

  return(
    <div className="products-dark min-h-screen p-4 lg:p-6" style={{background:'#080810',color:'#e4e4e7',fontFamily:"'DM Sans',-apple-system,sans-serif"}}>
      <style>{`@import url('https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700&family=JetBrains+Mono:wght@400;500&display=swap');.gl{background:rgba(255,255,255,0.03);backdrop-filter:blur(12px);border:1px solid rgba(255,255,255,0.06)}.fb{transition:width 0.8s ease-out}`}</style>
      <div className="max-w-[1800px] mx-auto">

        {/* ═══ GLOBAL STATUS BAR — visible during ALL operations ═══ */}
        {gStatus&&(<div className={`fixed top-0 left-0 right-0 z-50 px-4 py-2 ${gStatus.type==='working'?'bg-cyan-950/95':'bg-emerald-950/95'} backdrop-blur-md border-b border-white/10`}>
          <div className="max-w-[1800px] mx-auto flex items-center gap-4"><div className="flex-1"><div className="flex items-center justify-between mb-1"><span className="text-xs text-white font-medium">{gStatus.type==='working'?'⏳':'✅'} {gStatus.msg}</span><span className="text-xs text-white/70" style={{fontFamily:'JetBrains Mono,monospace'}}>{gStatus.progress}%</span></div><div className="w-full bg-black/30 rounded-full h-1.5"><div className="h-1.5 rounded-full transition-all duration-500" style={{width:`${gStatus.progress}%`,background:gStatus.type==='done'?'#22c55e':'linear-gradient(90deg,#06b6d4,#8b5cf6)'}}/></div></div>{gStatus.type==='done'&&<button onClick={()=>setGStatus(null)} className="text-white/50 hover:text-white text-lg">✕</button>}</div>
        </div>)}

        {/* ═══ HEADER ═══ */}
        <div className="flex items-center justify-between mb-5" style={{marginTop:gStatus?'48px':'0'}}>
          <div className="flex items-center gap-4"><div className="w-12 h-12 rounded-2xl flex items-center justify-center text-xl" style={{background:'linear-gradient(135deg,#06b6d4,#8b5cf6)',boxShadow:'0 8px 24px rgba(6,182,212,0.3)'}}>🎯</div><div><h1 className="text-2xl font-bold tracking-tight text-white">Product Sourcing Engine</h1><p className="text-xs text-zinc-500">Auto-Enrich · Template Descriptions · 80%+ Profit</p></div></div>
          <div className="flex items-center gap-3 text-[10px]"><span className="px-3 py-1.5 rounded-lg gl">Today: <strong className="text-cyan-400">{autoToday}</strong></span><span className="px-3 py-1.5 rounded-lg gl">7d: <strong className="text-cyan-400">0</strong></span></div>
        </div>

        {/* ═══ KPIs ═══ */}
        <div className="grid grid-cols-2 lg:grid-cols-6 gap-3 mb-5">
          {[{l:'Sourced',v:String(total),c:'#06b6d4'},{l:'In Shopify',v:String(inShop),c:'#22c55e'},{l:'Avg Markup',v:avgMu>0?`${avgMu}%`:'—',c:'#8b5cf6'},{l:'Flagged',v:String(flagN),c:flagN>0?'#f59e0b':'#3f3f46'},{l:'Bulk Passed',v:latestJob?latestJob.pass.toLocaleString():'0',c:'#22c55e'},{l:'Auto Source',v:autoOn?'ON':'OFF',c:autoOn?'#22c55e':'#ef4444'}].map((k,i)=>(
            <div key={i} className="gl rounded-xl p-3 text-center"><p className="text-xl font-bold" style={{color:k.c}}>{k.v}</p><p className="text-[9px] text-zinc-500 uppercase tracking-wider mt-0.5">{k.l}</p></div>
          ))}
        </div>

        {/* ═══ TABS ═══ */}
        <div className="flex gap-1.5 mb-5 overflow-x-auto pb-1">
          {([{id:'manual' as Tab,i:'🔍',l:'Manual Sourcing'},{id:'auto' as Tab,i:'⚡',l:'Auto Sourcing'},{id:'pricing' as Tab,i:'💰',l:'Pricing Logic'},{id:'bulk' as Tab,i:'📦',l:'Bulk Import'},{id:'products' as Tab,i:'📋',l:`Products (${total})`},{id:'history' as Tab,i:'📜',l:'History'}]).map(t=>(
            <button key={t.id} onClick={()=>setTab(t.id)} className={`px-4 py-2.5 rounded-xl text-xs font-semibold whitespace-nowrap transition-all ${tab===t.id?'text-white':'gl text-zinc-400 hover:text-white'}`} style={tab===t.id?{background:'linear-gradient(135deg,#06b6d4,#8b5cf6)',boxShadow:'0 4px 16px rgba(139,92,246,0.3)'}:{}}>{t.i} {t.l}</button>
          ))}
        </div>

        {/* ════════════════════════════════════════════════════════ */}
        {/* MANUAL SOURCING TAB (full original + grid)              */}
        {/* ════════════════════════════════════════════════════════ */}
        {tab==='manual'&&(<div className="space-y-4">
          <div className="gl rounded-2xl p-5">
            <div className="flex items-center justify-between mb-4"><h3 className="text-sm font-bold text-white">🎯 Discovery Criteria</h3><span className="text-[9px] px-2.5 py-1 rounded-full gl text-zinc-400">Auto: {autoOn?'ON':'OFF'}</span></div>
            <div className="grid grid-cols-2 lg:grid-cols-5 gap-3 mb-3"><Inp l="MIN COST ($)" v={crit.minP} k="minP" s="0.5"/><Inp l="MAX COST ($)" v={crit.maxP} k="maxP"/><Inp l="MAX RETAIL ($)" v={crit.maxRet} k="maxRet" s="5"/><Inp l="MIN MARKUP (%)" v={crit.minMu} k="minMu" s="5"/><Inp l="MIN $ PROFIT" v={crit.minDp} k="minDp" s="0.5"/></div>
            <div className="grid grid-cols-2 lg:grid-cols-5 gap-3 mb-3"><Inp l="MIN REVIEWS" v={crit.minRev} k="minRev"/><Inp l="MIN RATING" v={crit.minRat} k="minRat" s="0.1"/><Inp l="MAX BSR" v={crit.maxBsr} k="maxBsr"/><Inp l="MAX WEIGHT (lbs)" v={crit.maxWt} k="maxWt" s="0.5"/><div className="flex items-center gap-3 pt-5"><button onClick={()=>setCrit(p=>({...p,prime:!p.prime}))} className={`w-11 h-6 rounded-full transition-colors relative flex-shrink-0 ${crit.prime?'bg-cyan-500':'bg-zinc-700'}`}><div className={`w-5 h-5 bg-white rounded-full absolute top-0.5 transition-all ${crit.prime?'left-[22px]':'left-0.5'}`}/></button><span className="text-xs text-zinc-300">Prime Only</span></div></div>
            <div className="mb-3"><label className="text-[8px] text-zinc-500 uppercase tracking-wider block mb-1">BLOCKED WORDS</label><textarea value={crit.blocked} onChange={e=>setCrit(p=>({...p,blocked:e.target.value}))} rows={2} className="w-full px-3 py-2 bg-[#0c0c18] border border-zinc-800 rounded-lg text-[11px] text-zinc-300 focus:border-cyan-500 focus:outline-none resize-none" style={{fontFamily:'JetBrains Mono,monospace'}}/></div>
            <div className="mb-4 p-3 bg-[#0c0c18] rounded-xl border border-zinc-800/50"><p className="text-[8px] text-zinc-500 uppercase tracking-wider mb-2">TIERED MULTIPLIER</p><div className="flex gap-2">{DC.tiers.map((t,i)=>(<div key={i} className="flex-1 text-center p-2 rounded-lg gl"><p className="text-[10px] text-zinc-400">{t.label}</p><p className="text-lg font-bold text-cyan-400" style={{fontFamily:'JetBrains Mono,monospace'}}>{t.mult}x</p></div>))}</div></div>
            <div className="flex items-center justify-between"><div className="flex gap-2"><button onClick={runPreview} disabled={busy} className="px-5 py-2.5 rounded-xl text-sm font-semibold text-white disabled:opacity-50" style={{background:'linear-gradient(135deg,#22c55e,#16a34a)'}}>{busy?'⏳ Searching...':'🎯 Preview Products'}</button><button onClick={importAll} disabled={preview.length===0} className="px-5 py-2.5 rounded-xl text-sm font-semibold text-white disabled:opacity-30" style={{background:'linear-gradient(135deg,#06b6d4,#0891b2)'}}>⬇️ Import All ({preview.filter(p=>p.filter==='pass'||p.filter.startsWith('flag')).length})</button></div><button onClick={()=>setCrit({minP:3,maxP:25,minMu:80,minRev:500,minRat:3.5,maxBsr:100000,maxWt:5,maxRet:40,minDp:4,toSource:1000,prime:true,blocked:DC.blocked.join(', '),cats:[...DC.cats]})} className="px-3 py-2 gl rounded-lg text-[10px] text-zinc-400 hover:text-white">↩️ Reset</button></div>
          </div>
          {fstats&&(<div className="gl rounded-2xl p-5"><h4 className="text-sm font-bold text-white mb-3">📊 Filter Funnel — {fstats.total.toLocaleString()} analyzed</h4><div className="space-y-1.5">{[{l:'Raw from Keepa',v:fstats.total,c:'#71717a'},{l:'✓ Price $3-$25',v:fstats.price,c:'#06b6d4'},{l:'✓ No blocked brands',v:fstats.brand,c:'#06b6d4'},{l:'✓ 500+ reviews',v:fstats.reviews,c:'#06b6d4'},{l:'✓ 3.5+ rating',v:fstats.rating,c:'#06b6d4'},{l:'✓ Prime',v:fstats.prime,c:'#06b6d4'},{l:'✓ Under 5 lbs',v:fstats.weight,c:'#06b6d4'},{l:'✓ Safe category',v:fstats.cat,c:'#06b6d4'},{l:`✓ ${crit.minMu}%+ markup`,v:fstats.markup,c:'#8b5cf6'},{l:`✓ $${crit.minDp}+ profit`,v:fstats.profit,c:'#8b5cf6'},{l:`✓ Under $${crit.maxRet} retail`,v:fstats.retail,c:'#8b5cf6'},{l:'✓ Score 50+',v:fstats.score,c:'#22c55e'},{l:'🏁 SURVIVORS',v:fstats.final,c:'#22c55e'}].map((s,i)=>(<div key={i} className="flex items-center gap-3"><span className="text-[10px] text-zinc-400 w-40 truncate">{s.l}</span><div className="flex-1 bg-zinc-900 rounded-full h-4 overflow-hidden"><div className="h-full rounded-full fb" style={{width:`${(s.v/fstats.total)*100}%`,background:s.c}}/></div><span className="text-[10px] w-12 text-right" style={{color:s.c,fontFamily:'JetBrains Mono,monospace'}}>{s.v}</span></div>))}</div></div>)}
          {prevMode&&preview.length>0&&(<div className="gl rounded-2xl overflow-hidden"><div className="p-4 border-b border-zinc-800/50 flex items-center justify-between"><h4 className="text-sm font-bold text-white">🎯 Preview: {preview.length} survivors</h4><button onClick={importAll} className="px-4 py-2 rounded-lg text-xs font-semibold text-white" style={{background:'linear-gradient(135deg,#22c55e,#16a34a)'}}>↑ Import All → Shopify</button></div><div className="overflow-x-auto"><table className="w-full text-xs"><thead><tr className="border-b border-zinc-800/50 text-zinc-500 uppercase text-[8px]"><th className="p-3 text-left">St</th><th className="p-3 text-left">Product</th><th className="p-3 text-right">Amazon$</th><th className="p-3 text-right">Sell$</th><th className="p-3 text-right">Profit</th><th className="p-3 text-right">Markup</th><th className="p-3 text-right">Score</th><th className="p-3 text-center">Tier</th></tr></thead><tbody>{preview.map(p=>(<tr key={p.id} className="border-b border-zinc-800/30 hover:bg-white/[0.02]"><td className="p-3">{fb(p.filter)}</td><td className="p-3 max-w-[200px]"><p className="text-white font-medium truncate">{p.title}</p><p className="text-[9px] text-zinc-500">{p.asin} · ⭐{p.rating} ({p.reviews.toLocaleString()})</p></td><td className="p-3 text-right text-zinc-400" style={{fontFamily:'JetBrains Mono,monospace'}}>${p.amazonPrice.toFixed(2)}</td><td className="p-3 text-right text-emerald-400 font-semibold" style={{fontFamily:'JetBrains Mono,monospace'}}>${p.salePrice.toFixed(2)}</td><td className="p-3 text-right text-emerald-400" style={{fontFamily:'JetBrains Mono,monospace'}}>${p.dollarProfit.toFixed(2)}</td><td className="p-3 text-right"><span className={`font-semibold ${p.markupPct>=100?'text-emerald-400':'text-amber-400'}`}>{p.markupPct}%</span></td><td className="p-3 text-right"><span className={`font-semibold ${p.score>=80?'text-emerald-400':'text-amber-400'}`}>{p.score}</span></td><td className="p-3 text-center text-[9px] text-cyan-400">{p.multiplier}x</td></tr>))}</tbody></table></div></div>)}
          <div className="gl rounded-2xl px-5 py-3 flex items-center justify-between"><div className="flex items-center gap-4 text-xs"><span className="text-zinc-400 font-semibold uppercase tracking-wider">🛒 Shopify</span><span className="text-emerald-400 font-semibold">{inShop} active</span></div><div className="flex gap-2"><button onClick={pushSel} className="px-4 py-2 rounded-lg text-xs font-semibold text-white" style={{background:'linear-gradient(135deg,#22c55e,#16a34a)'}}>↑ Push All</button><button className="px-4 py-2 rounded-lg text-xs font-semibold gl text-cyan-400 border border-cyan-500/30">↓ Pull from Shopify</button></div></div>
          <div className="mt-2"><div className="flex items-center justify-between mb-4"><h3 className="text-sm font-bold text-white">📦 Products ({gridProducts.length})</h3><ViewToggle viewMode={viewMode} onViewModeChange={setViewMode} gridDensity={gridDensity} onGridDensityChange={setGridDensity} productCount={gridProducts.length}/></div><ProductCardGrid products={gridProducts} density={gridDensity} isLoading={gridLoading} selectedIds={gridSelectedIds} onSelectToggle={gst} onSelectAll={gsa} onDeselectAll={gda} onViewDetails={gvd} onRefresh={grf} onPause={gpa} onRemove={grm} onSyncShopify={gss} onBulkSync={gbs} onBulkActivate={gba} onBulkPause={gbp} onBulkExport={gbe} onBulkArchive={gbr}/></div>
        </div>)}

        {/* ════════════════════════════════════════════════════════ */}
        {/* AUTO SOURCING TAB (full original)                       */}
        {/* ════════════════════════════════════════════════════════ */}
        {tab==='auto'&&(<div className="space-y-4">
          <div className="gl rounded-2xl p-5"><div className="flex items-center justify-between mb-5"><h3 className="text-sm font-bold text-white">⚡ Automated Product Discovery</h3><button onClick={()=>setAutoOn(!autoOn)} className={`px-5 py-2.5 rounded-xl text-sm font-semibold transition-all ${autoOn?'text-white':'gl text-zinc-400'}`} style={autoOn?{background:'linear-gradient(135deg,#22c55e,#16a34a)'}:{}}>{autoOn?'✅ Running':'⏸️ Paused'}</button></div>
            <p className="text-xs text-zinc-500 mb-4">AI discovers products 6AM–11PM using Keepa batch → local filter → Rainforest on survivors.</p>
            <div className="grid grid-cols-2 lg:grid-cols-4 gap-4 mb-5"><div><label className="text-[8px] text-zinc-500 uppercase tracking-wider block mb-1">CHECK INTERVAL</label><select value={autoInt} onChange={e=>setAutoInt(Number(e.target.value))} className="w-full px-3 py-2.5 bg-[#0c0c18] border border-zinc-800 rounded-lg text-sm text-white"><option value={15}>Every 15 min</option><option value={30}>Every 30 min</option><option value={60}>Every hour</option></select></div><div><label className="text-[8px] text-zinc-500 uppercase tracking-wider block mb-1">MAX PER DAY</label><input type="number" value={autoMax} onChange={e=>setAutoMax(Number(e.target.value))} className="w-full px-3 py-2.5 bg-[#0c0c18] border border-zinc-800 rounded-lg text-sm text-white"/></div><div className="bg-[#0c0c18] rounded-lg p-3 border border-zinc-800 text-center"><p className="text-xl font-bold text-cyan-400">{autoToday}</p><p className="text-[9px] text-zinc-500">Sourced Today</p></div><div className="bg-[#0c0c18] rounded-lg p-3 border border-zinc-800 text-center"><p className="text-xl font-bold text-zinc-400">{autoLast?new Date(autoLast).toLocaleTimeString():'Never'}</p><p className="text-[9px] text-zinc-500">Last Run</p></div></div>
            <div className="bg-[#0c0c18] rounded-xl p-4 border border-zinc-800/50"><p className="text-xs font-semibold mb-3 text-white">📅 Schedule — 6AM to 11PM</p><div className="grid grid-cols-6 lg:grid-cols-12 gap-1">{Array.from({length:24},(_,h)=>{const on=autoOn&&h>=6&&h<=23;return<div key={h} className={`rounded-lg p-1.5 text-center text-[8px] ${on?'bg-cyan-500/10 border border-cyan-500/20 text-cyan-400':'bg-zinc-900 border border-zinc-800 text-zinc-600'}`}><p className="font-bold">{h}:00</p><p>{on?'✓':'—'}</p></div>;})}</div></div>
          </div>
        </div>)}

        {/* ════════════════════════════════════════════════════════ */}
        {/* PRICING LOGIC TAB (full original)                       */}
        {/* ════════════════════════════════════════════════════════ */}
        {tab==='pricing'&&(<div className="space-y-4"><div className="gl rounded-2xl p-5"><div className="flex items-center justify-between mb-4"><h3 className="text-sm font-bold text-white">💰 Pricing Rules Engine</h3><button onClick={()=>{setProducts(prev=>prev.map(p=>{const r=calcPrice(p.amazonPrice,crit.maxRet);return{...p,salePrice:r.sp,dollarProfit:r.dp,markupPct:r.mp,multiplier:r.mult};}));}} className="px-4 py-2 rounded-xl text-xs font-semibold text-white" style={{background:'linear-gradient(135deg,#f59e0b,#d97706)'}}>🔄 Recalculate All</button></div>
          <div className="grid grid-cols-2 lg:grid-cols-4 gap-3 mb-4">{DC.tiers.map((t,i)=>(<div key={i} className="bg-[#0c0c18] rounded-xl p-4 border border-zinc-800 text-center"><p className="text-[10px] text-zinc-500 uppercase">Amazon Cost</p><p className="text-lg font-bold text-white">{t.label}</p><p className="text-3xl font-bold text-cyan-400 my-2" style={{fontFamily:'JetBrains Mono,monospace'}}>{t.mult}x</p></div>))}</div>
          <div className="space-y-2">{[{n:'1. Tiered Multiplier',d:'Apply multiplier based on cost tier',v:'See tiers'},{n:'2. Min 80% Markup',d:'Reject if markup below 80%',v:'80% floor'},{n:'3. Min $4 Profit',d:'Reject if dollar profit < $4',v:'$4.00'},{n:'4. Retail Cap $40',d:'Sale price cannot exceed $40',v:`$${crit.maxRet}`},{n:'5. Round to .99',d:'Psychology pricing',v:'.99'},{n:'6. Compare-at = Max Competitor',d:'Strike-through pricing',v:'Max comp'},{n:'7. Cost = Amazon Price',d:'Shopify margin tracking',v:'Auto'}].map((r,i)=>(<div key={i} className="flex items-center gap-4 p-3 bg-[#0c0c18] rounded-xl border border-cyan-500/10"><span className="text-sm font-bold text-zinc-500 w-6">#{i+1}</span><div className="w-10 h-5 rounded-full relative bg-cyan-500"><div className="w-4 h-4 bg-white rounded-full absolute top-0.5 left-[22px]"/></div><div className="flex-1"><p className="text-sm font-semibold text-white">{r.n}</p><p className="text-[10px] text-zinc-500">{r.d}</p></div><span className="text-xs px-3 py-1 rounded-lg gl text-cyan-400" style={{fontFamily:'JetBrains Mono,monospace'}}>{r.v}</span></div>))}</div>
        </div></div>)}

        {/* ════════════════════════════════════════════════════════ */}
        {/* BULK IMPORT TAB (enhanced with results + card/table)    */}
        {/* ════════════════════════════════════════════════════════ */}
        {tab==='bulk'&&(<div className="space-y-4">
          <div className="gl rounded-2xl p-5"><h3 className="text-sm font-bold text-white mb-2">📦 Bulk Import + Auto-Enrich</h3><p className="text-xs text-zinc-500 mb-4">Upload → Filter → Generate descriptions → Fill ALL missing data → Ready for Shopify</p>
            <div className="grid grid-cols-1 lg:grid-cols-2 gap-3 mb-4"><div className="bg-[#0c0c18] rounded-xl p-4 border border-cyan-500/20"><p className="text-xs font-bold text-cyan-400 mb-1">Format A: ASIN-Only</p><p className="text-[9px] text-zinc-500">2 columns: URL + ASIN. Full enrichment pipeline.</p></div><div className="bg-[#0c0c18] rounded-xl p-4 border border-violet-500/20"><p className="text-xs font-bold text-violet-400 mb-1">Format B: Shopify Export</p><p className="text-[9px] text-zinc-500">166 columns. Price-checks + fills gaps + replaces eBay descriptions.</p></div></div>
            <div className="border-2 border-dashed border-zinc-700 rounded-2xl p-8 text-center hover:border-cyan-500/50 transition-colors cursor-pointer" onClick={()=>fref.current?.click()}><input type="file" ref={fref} onChange={handleBulk} accept=".csv,.xlsx,.xls,.tsv" className="hidden"/><p className="text-3xl mb-2">📤</p><p className="text-sm font-semibold text-zinc-300">Drop spreadsheet or click to browse</p><p className="text-[10px] text-zinc-500 mt-1">CSV, XLSX, TSV · Up to 100K rows</p></div>
            <div className="mt-3 bg-[#0c0c18] rounded-xl p-3 border border-zinc-800/50"><p className="text-[8px] text-zinc-500 uppercase tracking-wider mb-1.5">PIPELINE</p><div className="flex items-center gap-1 text-[8px] flex-wrap">{['Parse','→','Keepa','→','Filter','→','Score','→','Gen Descriptions','→','Fill Cost/URLs/Qty','→','Validate','→','Done'].map((s,i)=>s==='→'?<span key={i} className="text-zinc-600">→</span>:<span key={i} className="px-1.5 py-0.5 rounded bg-zinc-800 text-zinc-400">{s}</span>)}</div></div>
          </div>
          {jobs.map(j=>(<div key={j.id} className="gl rounded-2xl p-4"><div className="flex items-center justify-between mb-2"><div><p className="text-sm font-semibold text-white">{j.file}</p><p className="text-[9px] text-zinc-500">{j.fmt==='asin'?'ASIN-Only':'Shopify Export'} · {j.unique.toLocaleString()} unique</p></div><span className={`text-[9px] px-2 py-0.5 rounded-full ${j.status==='done'?'bg-emerald-500/15 text-emerald-400':'bg-cyan-500/15 text-cyan-400'}`}>{j.status}</span></div><div className="w-full bg-zinc-800 rounded-full h-2 mb-2"><div className="h-2 rounded-full transition-all" style={{width:j.unique>0?`${(j.done/j.unique)*100}%`:'0%',background:'linear-gradient(90deg,#06b6d4,#8b5cf6)'}}/></div><p className="text-[10px] text-zinc-400 mb-2">{j.stage}</p>{j.status==='done'&&<div className="flex gap-3 text-[10px]"><span className="text-emerald-400">✅ {j.pass.toLocaleString()} passed</span><span className="text-red-400">✗ {j.fail.toLocaleString()} failed</span><span className="text-amber-400">⚠️ {j.flag} flagged</span></div>}</div>))}

          {/* ═══ BULK RESULTS: Filter bar + Card/Table toggle ═══ */}
          {latestJob&&latestJob.products&&(<>
            <div className="gl rounded-2xl p-3"><div className="flex items-center gap-3 mb-2.5 flex-wrap"><div className="flex-1 min-w-[220px] relative"><span className="absolute left-3 top-1/2 -translate-y-1/2 text-zinc-600 text-sm">🔍</span><input value={bulkSearch} onChange={e=>setBulkSearch(e.target.value)} placeholder="Search by title, ASIN, or description..." className="w-full pl-9 pr-3 py-2 bg-[#0c0c18] border border-zinc-800 rounded-lg text-xs text-white placeholder:text-zinc-600 focus:border-cyan-500 focus:outline-none"/></div></div>
              <div className="flex items-center gap-2 flex-wrap">
                <select value={bulkMargin} onChange={e=>setBulkMargin(e.target.value)} className="px-3 py-1.5 bg-[#0c0c18] border border-zinc-800 rounded-lg text-[10px] text-white"><option value="all">All Margins</option><option value="high">High (&gt;100%)</option><option value="medium">Medium (50-100%)</option><option value="low">Low (&lt;50%)</option></select>
                <select value={bulkCat} onChange={e=>setBulkCat(e.target.value)} className="px-3 py-1.5 bg-[#0c0c18] border border-zinc-800 rounded-lg text-[10px] text-white"><option value="all">All Categories</option>{bulkCats.map(c=><option key={c} value={c}>{c}</option>)}</select>
                <label className="flex items-center gap-1.5 px-2.5 py-1.5 rounded-lg gl text-[10px] cursor-pointer"><input type="checkbox" checked={staleOnly} onChange={()=>setStaleOnly(!staleOnly)} className="accent-cyan-500 w-3 h-3"/><span className="text-zinc-300">Stale only</span></label>
                <label className="flex items-center gap-1.5 px-2.5 py-1.5 rounded-lg gl text-[10px] cursor-pointer"><input type="checkbox" checked={shopSynced} onChange={()=>setShopSynced(!shopSynced)} className="accent-cyan-500 w-3 h-3"/><span className="text-zinc-300">Shopify synced</span></label>
                <div className="ml-auto flex items-center gap-2"><span className="text-[9px] text-zinc-500">Sort:</span><select value={bulkSort} onChange={e=>setBulkSort(e.target.value)} className="px-2 py-1.5 bg-[#0c0c18] border border-zinc-800 rounded-lg text-[10px] text-white"><option value="score">Listing Score</option><option value="updated">Last Updated</option><option value="price_asc">Price ↑</option><option value="price_desc">Price ↓</option><option value="profit">Profit ↓</option></select>
                  <div className="flex border border-zinc-800 rounded-lg overflow-hidden"><button onClick={()=>setPView('card')} className={`px-2.5 py-1.5 text-[10px] ${pView==='card'?'bg-cyan-500/20 text-cyan-400':'text-zinc-500'}`}>▦ Cards</button><button onClick={()=>setPView('table')} className={`px-2.5 py-1.5 text-[10px] ${pView==='table'?'bg-cyan-500/20 text-cyan-400':'text-zinc-500'}`}>☰ Table</button></div></div>
              </div>
            </div>
            <p className="text-[10px] text-zinc-500">{filteredBulk.length} of {latestJob.products.length} products · Descriptions generated · Data enriched</p>

            {/* TABLE VIEW */}
            {pView==='table'&&(<div className="gl rounded-2xl overflow-hidden"><div className="overflow-x-auto"><table className="w-full text-xs"><thead><tr className="border-b border-zinc-800/50 text-zinc-500 uppercase text-[8px]"><th className="p-2.5 w-10"></th><th className="p-2.5 text-left">Product</th><th className="p-2.5 text-right">Sale</th><th className="p-2.5 text-right">Amazon</th><th className="p-2.5 text-right">Profit</th><th className="p-2.5 text-center">Score</th><th className="p-2.5 text-center">Desc</th><th className="p-2.5 text-center">Price Check</th><th className="p-2.5 text-center">Issues</th></tr></thead><tbody>
              {filteredBulk.map(p=>{const sc=listingScore(p);const issues=listingIssues(p);const profit=p.compareAt-p.salePrice;const pct=Math.round((profit/p.salePrice)*100);return(<tr key={p.id} className="border-b border-zinc-800/30 hover:bg-white/[0.02] cursor-pointer" onClick={()=>setExpandId(expandId===p.id?null:p.id)}><td className="p-2.5"><div className="w-9 h-9 rounded-lg overflow-hidden bg-zinc-900 border border-zinc-800"><img src={p.image} alt="" className="w-full h-full object-cover" onError={e=>{(e.target as HTMLImageElement).style.display='none'}}/></div></td><td className="p-2.5 max-w-[280px]"><p className="text-white font-medium truncate text-[11px]">{p.title}</p><p className="text-[9px] text-zinc-500" style={{fontFamily:'JetBrains Mono,monospace'}}>{p.asin} · {p.vendor}</p></td><td className="p-2.5 text-right text-emerald-400 font-semibold" style={{fontFamily:'JetBrains Mono,monospace'}}>${p.salePrice.toFixed(2)}</td><td className="p-2.5 text-right text-cyan-400" style={{fontFamily:'JetBrains Mono,monospace'}}>${p.amazonPrice.toFixed(2)}</td><td className="p-2.5 text-right"><span className="text-emerald-400 font-semibold" style={{fontFamily:'JetBrains Mono,monospace'}}>${profit.toFixed(2)}</span><span className="text-[8px] text-zinc-500 ml-1">({pct}%)</span></td><td className="p-2.5 text-center"><ScoreRing score={sc}/></td><td className="p-2.5 text-center"><span className="text-[8px] px-1.5 py-0.5 rounded-full bg-emerald-500/15 text-emerald-400 font-bold">Generated</span></td><td className="p-2.5 text-center"><span className={`text-[9px] ${(Date.now()-new Date(p.priceChecked).getTime())>7*864e5?'text-red-400':'text-zinc-400'}`}>{sinceStr(p.priceChecked)}</span></td><td className="p-2.5 text-center">{issues.length>0?<span className="text-[8px] px-1.5 py-0.5 rounded-full bg-amber-500/15 text-amber-400">{issues.length}</span>:<span className="text-emerald-400">✓</span>}</td></tr>);})}
            </tbody></table></div></div>)}

            {/* CARD VIEW */}
            {pView==='card'&&(<div className="grid grid-cols-1 lg:grid-cols-2 xl:grid-cols-3 gap-3">
              {filteredBulk.map(p=>{const sc=listingScore(p);const issues=listingIssues(p);const profit=p.compareAt-p.salePrice;const pct=Math.round((profit/p.salePrice)*100);const stale=(Date.now()-new Date(p.priceChecked).getTime())>7*864e5;return(
                <div key={p.id} className="gl rounded-xl overflow-hidden hover:border-cyan-500/20 transition-all">
                  <div className="flex gap-3 p-3"><div className="w-[72px] h-[72px] rounded-lg overflow-hidden bg-zinc-900 flex-shrink-0 border border-zinc-800"><img src={p.image} alt="" className="w-full h-full object-cover" onError={e=>{(e.target as HTMLImageElement).style.display='none'}}/></div>
                    <div className="flex-1 min-w-0"><div className="flex items-start justify-between gap-2"><div className="min-w-0"><p className="text-[11px] font-semibold text-white truncate">{p.title}</p><p className="text-[8px] text-zinc-500 mt-0.5" style={{fontFamily:'JetBrains Mono,monospace'}}>{p.asin} · {p.vendor} · {p.category}</p></div><ScoreRing score={sc}/></div>
                      <div className="flex items-center gap-3 mt-1.5 text-[10px]"><span className="text-emerald-400 font-bold" style={{fontFamily:'JetBrains Mono,monospace'}}>${p.salePrice.toFixed(2)}</span><span className="text-zinc-500 line-through" style={{fontFamily:'JetBrains Mono,monospace'}}>${p.compareAt.toFixed(2)}</span><span className="px-1.5 py-0.5 rounded bg-emerald-500/10 text-emerald-400 text-[8px] font-bold">+${profit.toFixed(2)} ({pct}%)</span></div>
                      <div className="flex items-center gap-2 mt-1.5 text-[9px]">{p.amazonPrice>0&&<span className="text-zinc-400">AMZ:<span className="text-cyan-400 ml-0.5" style={{fontFamily:'JetBrains Mono,monospace'}}>${p.amazonPrice}</span></span>}{p.ebayPrice>0&&<span className="text-zinc-400">eBay:<span className="text-zinc-300 ml-0.5">${p.ebayPrice}</span></span>}{p.costcoPrice>0&&<span className="text-zinc-400">Costco:<span className="text-zinc-300 ml-0.5">${p.costcoPrice}</span></span>}</div>
                    </div>
                  </div>
                  <div className="px-3 pb-2 flex items-center justify-between"><div className="flex items-center gap-1.5"><span className="text-[7px] px-1.5 py-0.5 rounded-full bg-emerald-500/15 text-emerald-400 font-bold">✓ Image</span><span className="text-[7px] px-1.5 py-0.5 rounded-full bg-emerald-500/15 text-emerald-400 font-bold">✓ Description</span><span className="text-[7px] px-1.5 py-0.5 rounded-full bg-emerald-500/15 text-emerald-400 font-bold">✓ Cost</span><span className="text-[7px] px-1.5 py-0.5 rounded-full bg-emerald-500/15 text-emerald-400 font-bold">✓ URL</span>{issues.length>0&&<span className="text-[7px] px-1.5 py-0.5 rounded-full bg-amber-500/15 text-amber-400 font-bold">{issues.length} issues</span>}</div><span className={`text-[8px] ${stale?'text-red-400':'text-zinc-500'}`}>🕐 {sinceStr(p.priceChecked)}</span></div>
                  <div className="px-3 pb-2 flex gap-2"><button onClick={()=>setDescPreviewId(descPreviewId===p.id?null:p.id)} className="text-[8px] text-cyan-400 hover:underline">Preview description</button>{issues.length>0&&<button onClick={()=>setExpandId(expandId===p.id?null:p.id)} className="text-[8px] text-amber-400 hover:underline">View issues</button>}</div>
                  {descPreviewId===p.id&&(<div className="mx-3 mb-3 p-3 rounded-lg bg-[#0c0c18] border border-cyan-500/20 text-[10px] text-zinc-300 space-y-2"><div className="flex items-center justify-between"><span className="text-[8px] text-cyan-400 uppercase font-bold">Generated Shopify Description</span><span className="text-[7px] px-1.5 py-0.5 rounded bg-cyan-500/10 text-cyan-400">Replaced eBay/AutoDS template</span></div><div dangerouslySetInnerHTML={{__html:genDesc(p)}} className="[&_h3]:text-xs [&_h3]:font-bold [&_h3]:text-white [&_h3]:mt-2 [&_h3]:mb-1 [&_ul]:space-y-1 [&_li]:text-[10px] [&_p]:text-[10px] [&_p]:text-zinc-400"/></div>)}
                  {expandId===p.id&&issues.length>0&&(<div className="mx-3 mb-3 p-3 rounded-lg bg-amber-500/5 border border-amber-500/15 space-y-1">{issues.map((iss,i)=><p key={i} className="text-[9px] text-amber-400"><span className="text-amber-500">⚠</span> {iss}</p>)}</div>)}
                </div>
              );})}
            </div>)}
          </>)}
        </div>)}

        {/* ════════════════════════════════════════════════════════ */}
        {/* PRODUCTS TAB (original with search/filter)              */}
        {/* ════════════════════════════════════════════════════════ */}
        {tab==='products'&&(<div className="space-y-4">
          <div className="gl rounded-2xl px-4 py-3 flex items-center gap-3 flex-wrap"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search products or ASIN..." className="flex-1 min-w-[200px] px-4 py-2 bg-[#0c0c18] border border-zinc-800 rounded-lg text-sm text-white placeholder:text-zinc-600 focus:border-cyan-500 focus:outline-none"/><div className="flex gap-1">{[{k:'all',l:'All'},{k:'active',l:'Active'},{k:'flagged',l:'Flagged'},{k:'oos',l:'OOS'}].map(f=><button key={f.k} onClick={()=>setFilt(f.k)} className={`px-3 py-1.5 rounded-lg text-[10px] font-semibold ${filt===f.k?'bg-cyan-500/15 text-cyan-400 border border-cyan-500/30':'gl text-zinc-400'}`}>{f.l}</button>)}</div><button onClick={()=>{setPcheck(true);setGStatus({msg:'Checking prices...',progress:50,type:'working'});setTimeout(()=>{setProducts(p=>p.map(x=>({...x,lastCheck:new Date().toISOString()})));setPcheck(false);setGStatus({msg:'Price check complete',progress:100,type:'done'});setTimeout(()=>setGStatus(null),5000);},3000);}} disabled={pcheck} className="px-4 py-2 rounded-lg text-xs font-semibold text-white disabled:opacity-50" style={{background:'linear-gradient(135deg,#f59e0b,#d97706)'}}>{pcheck?'⏳ Checking...':'🔄 Check Prices'}</button><button onClick={pushSel} className="px-4 py-2 rounded-lg text-xs font-semibold text-white" style={{background:'linear-gradient(135deg,#22c55e,#16a34a)'}}>↑ Push Selected</button></div>
          <div className="gl rounded-2xl overflow-hidden"><div className="overflow-x-auto"><table className="w-full text-xs"><thead><tr className="border-b border-zinc-800/50 text-zinc-500 uppercase text-[8px]"><th className="p-3"><input type="checkbox" checked={selAll} onChange={()=>{const n=!selAll;setSelAll(n);setProducts(p=>p.map(x=>({...x,sel:n})));}} className="accent-cyan-500"/></th><th className="p-3 text-left">Product</th><th className="p-3 text-right">Cost</th><th className="p-3 text-right">Sale$</th><th className="p-3 text-right">Profit</th><th className="p-3 text-right">Markup</th><th className="p-3 text-center">Stock</th><th className="p-3 text-center">Shopify</th></tr></thead><tbody>{dsp.length===0?<tr><td colSpan={8} className="p-8 text-center text-zinc-500">No products yet. Use Manual, Auto, or Bulk Import.</td></tr>:dsp.map(p=>(<tr key={p.id} className={`border-b border-zinc-800/30 hover:bg-white/[0.02] ${p.sel?'bg-cyan-500/5':''}`}><td className="p-3"><input type="checkbox" checked={p.sel} onChange={()=>setProducts(prev=>prev.map(x=>x.id===p.id?{...x,sel:!x.sel}:x))} className="accent-cyan-500"/></td><td className="p-3 max-w-[200px]"><p className="text-white font-medium truncate">{p.title}</p><p className="text-[9px] text-zinc-500">{p.asin}</p></td><td className="p-3 text-right text-zinc-400" style={{fontFamily:'JetBrains Mono,monospace'}}>${p.costPrice.toFixed(2)}</td><td className="p-3 text-right text-emerald-400 font-semibold" style={{fontFamily:'JetBrains Mono,monospace'}}>${p.salePrice.toFixed(2)}</td><td className="p-3 text-right text-emerald-400" style={{fontFamily:'JetBrains Mono,monospace'}}>${p.dollarProfit.toFixed(2)}</td><td className="p-3 text-right"><span className={`font-semibold ${p.markupPct>=100?'text-emerald-400':'text-amber-400'}`}>{p.markupPct}%</span></td><td className="p-3 text-center"><span className={`text-[8px] px-1.5 py-0.5 rounded-full ${p.avail==='in_stock'?'bg-emerald-500/15 text-emerald-400':'bg-red-500/15 text-red-400'}`}>{p.avail==='in_stock'?'In Stock':'OOS'}</span></td><td className="p-3 text-center"><span className={`text-[8px] px-1.5 py-0.5 rounded-full ${p.shopStatus==='active'?'bg-emerald-500/15 text-emerald-400':'bg-zinc-500/15 text-zinc-400'}`}>{p.shopStatus}</span></td></tr>))}</tbody></table></div></div>
        </div>)}

        {/* ═══ HISTORY TAB ═══ */}
        {tab==='history'&&(<div className="gl rounded-2xl p-5"><h3 className="text-sm font-bold text-white mb-4">📜 History</h3><div className="space-y-2">{[{t:'Now',a:'Page loaded',ty:'system'},{t:'—',a:'Weekly price check: Sundays 3AM',ty:'schedule'},{t:'—',a:'Description template: auto-replaces eBay/AutoDS on import',ty:'rule'},{t:'—',a:'Never push without: image + description + cost + supplier URL',ty:'rule'},{t:'—',a:'Below 80% markup: 48hr grace → auto-disable',ty:'rule'}].map((h,i)=>(<div key={i} className="flex items-center gap-3 p-3 bg-[#0c0c18] rounded-lg border border-zinc-800"><span className="text-[10px] text-zinc-500 w-12" style={{fontFamily:'JetBrains Mono,monospace'}}>{h.t}</span><span className={`text-[8px] px-2 py-0.5 rounded-full uppercase font-bold ${h.ty==='system'?'bg-cyan-500/15 text-cyan-400':h.ty==='schedule'?'bg-violet-500/15 text-violet-400':'bg-amber-500/15 text-amber-400'}`}>{h.ty}</span><span className="text-xs text-zinc-300">{h.a}</span></div>))}</div></div>)}

      </div>
    </div>
  );
}

